#!/bin/bash

thisdir=$(dirname $(readlink -f $0))

set -eo pipefail

eval $(cat $thisdir/production.env.vars 2>/dev/null)

# Prompt for new env vars like so:
# read new_var
# if [ -z "$new_var" ]
# then
#     MY_VAR="$MY_VAR"
# else
#     MY_VAR="$new_var"
# fi
# echo "export MY_VAR='${MY_VAR}'" > $thisdir/production.env.vars
# echo "MY_VAR = $MY_VAR"

set -u

cd $thisdir"/.."
mkdir -p dist dist-previous
mv -f dist/* dist-previous/ 2>/dev/null || :

# Add MY_VAR="${MY_VAR}" etc to the beginning of this line:
NODE_ENV=production yarn run build

du -skh dist
tree -sh dist -I assets
